# -*- coding: utf-8 -*-
"""Project 1 Blackjack - Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCPkZPyVsGx7QPFvQwqjLIEGTahNJHFK
"""

#----------------------------------------
#  CSC 315 / 615 Spring 2023
#  Project 1 Blackjack
#
# Chris Eagar <<put your name here
#----------------------------------------


#------
# import used for shuffling deck
#  do not change
#------
import itertools, random




#------------
# PrintCard
#   this function prints a card (number,suit)
#   in the form of "Ace of Spade" or "3 of Diamond"
#------------
def PrintCard(card):

  #
  # ToDo: delete the following line of code
  #  and implement this function
  #

  if(card[0] == 1):
    num = str('Ace')
  elif(card[0] == 11):
    num = str('Jack')
  elif(card[0] == 12):
    num = str('Queen')
  elif(card[0] == 13):
    num = str('King')
  elif(card != 1|11|12|13):
    num = card[0]

  print("  ", num, "of", card[1])


#------------
# HandValue
#   input:   a list of cards called a hand
#   output:  a number describing the value of the hand
#------------

def HandValue(hand):

  #
  # ToDo: delete the following line of code
  #  and implement this function

  return 0;

#----------------------------------------
# Main execution starts here
#----------------------------------------

#------------
# Construct a deck and shuffle it.
#  shuffle code from Python example
#  do not modify
#------------
deck = list(itertools.product(range(1,14),['Spade','Heart','Diamond','Club']))
random.shuffle(deck)

#---------
# Main game loop to play Blackjack
#  Implement the main pseudocode here
#
# ToDo:  You must heavily modify the following
#
#---------

hand = []   # hand is empty
cardidx=0
value = 0
playagain = False
exit = False

#First set of cards when first game starts
print("Dealer has 18:")
print("You have: ")
for i in range(2):
  card = deck[cardidx]
  cardidx = cardidx+1
  (PrintCard(card))
  hand.append(card)

  initial = card[0]
  if(initial > 10):
    value = value + 10
  elif(initial == 1):
    value = value + 11
  else:
    value = value + card[0]
  i = i+2

print("Value:", value)


#Check if cards equal or go over 21
if(value == 21):

  print("Blackjack, you win!")
  playagain = input ("Play again? 1: Yes 2: No")
  while (playagain != '1' and playagain != '2'):
    playagain = input("Play again? 1: Yes 2: No")

  if playagain=='1':
    playagain = True

  if playagain=='2':
    keepplaying = False
    exit = True

elif(value > 21):

  print("Busted, you lose!")
  playagain = input("Play again? 1: Yes 2: No")
  while(playagain != '1' and playagain != '2'):
    playagain = input("Play again? 1: Yes 2: No")

  if playagain=='1':
    playagain = True

  if playagain == '2':
    keepplaying = False
    exit = True

while (cardidx<len(deck) and exit == False):

  keepplaying = True

  if (playagain == True):
    print("----------------------------")
    value = 0
    print("Dealer has 18:")
    print("You have: ")
    for i in range(2):
      card = deck[cardidx]
      cardidx = cardidx+1
      (PrintCard(card))
      hand.append(card)

      initial = card[0]
      if(initial > 10):
        value = value + 10
      elif(initial == 1):
        value = value + 11
      else:
        value = value + card[0]
      i = i+2
      playagain = False

    print("Value:", value)

    if(value == 21):
      print("Blackjack, you win!")
      playagain = input ("Play again? 1: Yes 2: No ")
      while (playagain != '1' and playagain != '2'):
        playagain = input("Play again? 1: Yes 2: No ")

      if playagain=='1':
        keepplaying = False
        playagain = True

      if playagain=='2':
        keepplaying = False
        exit = True

    elif(value > 21):
      print("Busted, you lose!")
      playagain = input("Play again? 1: Yes 2: No ")
      while(playagain != '1' and playagain != '2'):
        playagain = input("Play again? 1: Yes 2: No ")

      if playagain == '1':
        keepplaying = False
        playagain = True

      if playagain == '2':
        keepplaying = False
        exit = True


  while(keepplaying == True):
    hitorstay = input("What to do? 1: Hit 2: Stay ")
    while (hitorstay != '1' and hitorstay != '2'):
      hitorstay = input("What to do? 1: Hit 2: Stay ")

    if (hitorstay == '1'):
      card = deck[cardidx]
      cardidx = cardidx+1
      (PrintCard(card))
      hand.append(card)

      initial = card[0]
      if(initial > 10):
        value = value + 10
      elif(initial == 1):
        value = value + 11
      else:
        value = value + card[0]

      print("Value:", value)

      if(value > 21):
        print("Busted, you lose!")
        playagain = input ("Play again? 1: Yes 2: No ")
        while (playagain != '1' and playagain != '2'):
          playagain = input("Play again? 1: Yes 2: No ")

        if playagain == '1':
          keepplaying = False
          playagain = True

        if playagain=='2':
          keepplaying = False
          exit = True

      if(value == 21):
        print("Blackjack, you win!")
        playagain = input ("Play again? 1: Yes 2: No ")
        while (playagain != '1' and playagain != '2'):
          playagain = input("Play again? 1: Yes 2: No ")

        if playagain == '1':
          keepplaying = False
          playagain = True

        if playagain=='2':
          keepplaying = False
          exit = True

    elif(hitorstay == '2'):
      if(value < 18):
        print("You came short, you lose!")
        playagain = input ("Play again? 1: Yes 2: No ")
        while (playagain != '1' and playagain != '2'):
          playagain = input("Play again? 1: Yes 2: No ")

        if playagain == '1':
          keepplaying = False
          playagain = True

        if playagain=='2':
          keepplaying = False
          exit = True

      elif(value > 18 & value < 21):
        print("You beat 18, you win!")
        playagain = input ("Play again? 1: Yes 2: No ")
        while (playagain != '1' and playagain != '2'):
          playagain = input("Play again? 1: Yes 2: No ")

        if playagain == '1':
          keepplaying = False
          playagain = True

        if playagain=='2':
          keepplaying = False
          exit = True

      elif(value == 18):
        print("You tied 18, push!")
        playagain = input ("Play again? 1: Yes 2: No ")
        while (playagain != '1' and playagain != '2'):
          playagain = input("Play again? 1: Yes 2: No ")

        if playagain == '1':
          keepplaying = False
          playagain = True

        if playagain=='2':
          keepplaying = False
          exit = True

print("Goodbye!")